const menu = [
    {
      id: 1,
      title: 'Blockchain Cryptocurrency Fundamentals',
      earn: 30,
      heading:  'Intro to Blockchain',
      numerator:  '8.3',
      denominator: '10',
      percent: 15.99,
    },
    {
        id: 2,
      title: 'Blockchain Cryptocurrency Fundamentals',
      earn: 30,
      heading:  'Intro to Blockchain',
      numerator:  '8.3',
      denominator: '10',
      percent: 15.99,
    },
    {
        id: 3,
        title: 'Blockchain Cryptocurrency Fundamentals',
        earn: 30,
        heading:  'Intro to Blockchain',
        numerator:  '8.3',
        denominator: '10',
        percent: 15.99,
    },
    {
      id: 4,
      title: 'Blockchain Cryptocurrency Fundamentals',
      earn: 30,
      heading:  'Intro to Blockchain',
      numerator:  '8.3',
      denominator: '10',
      percent: 15.99,
  },
  {
    id: 5,
    title: 'Blockchain Cryptocurrency Fundamentals',
    earn: 30,
    heading:  'Intro to Blockchain',
    numerator:  '8.3',
    denominator: '10',
    percent: 15.99,
},
]
export default menu;